### ISSUE TITLE
[CATA] [BATTLEGROUNDS] Bg system problem with the queue. 

### ISSUE THREAD

**Issue by Cannonbow** [NRG-Wow/NRGWow-Bugtracker#177]
Reporter Name:Cannonbow

Description:Well the Battleground Queue system allows you to join bg when we get 4 ppl it means 2v2 sometimes we get 3v2 or 4v2 on eye of the storm so probability to lose is 100% (unfair)

Expected behavior: bgs should be fair also balanced for example we had 3v3 our team had 3 dps and other team 2 healers and 1 dps it's unbalanced

Steps to follow:
1.queue bg
2. We get 4/4 battleground open you enter
3.when someone queue the bg system say 1/4 it should change to 2/2 when bg is already started or to 2/4 to be fair and get balanced time or same numbers or players
4.good luck on fighting xD

**Comment by Illusie** [comment]
You can't balance it out no matter what aslong the que require to pop bg is lower than 5v5 even 5v5 is not the optimal to pop bg.
its population problem.

I had many times situation when 3v1 2v1 / someone leave / not join
and even 2v2 when ungear vs geared which is instant lose
because it make the BG requirements more on the  individual player skill than play a part/role as a team.

the game is like real life - unfair.

**Comment by Cannonbow** [comment]
Yeah true I think there is no solution for this xD so we should wait for population to increase bcs population =full bg and pvp

**Comment by Wilcalaf** [comment]
This was issue was addressed with the disable of premade groups to BGs.
But as stated by @Illusie Its mostly a population problem.
Ill assume this addressed by the momentarily disable of premade however since its not a core bug just a population issue im going to close the issue
