### ISSUE TITLE
[CATA][Talents][Paladin] Ardent Defender

### ISSUE THREAD

**Issue by Gubbyfishy** [NRG-Wow/NRGWow-Bugtracker#205]
**Reporter(Player/Character) Name**: Hundoslavus

**Description**: Ardent Defender does not properly prevent a fatal hit

**Current behaviour**: The paladin straight up flops over dead instead.

**Expected behaviour**: A visual effect should play and you should go back to 15% of maximum health.

**Steps to reproduce the problem**:

1. Cast Ardent Defender
2. Take a fatal hit
3. The Paladin instead straight up dies.

**Comment by virpyre** [comment]
I loved this spell before the Cataclysm patch, I was a little underwhelmed with the new design - it was a huuuuge nerf with damage reduction and survivability from the old passive model and auto life it now heals only when you would otherwise die in that 10 sec.

**To Dev:** [Ardent Defender](http://cata-shoot.tauri.hu/?spell=31850) reduces all damage taken by 20% for 10 seconds. Any killing blow will consume AD effect, [healing the paladin for 15%](http://cata-shoot.tauri.hu/?spell=66235).

**Comment by Wilcalaf** [comment]
what does "flop over dead" means?

**Comment by Gubbyfishy** [comment]
@Wilcalaf Lmao sorry. It means you will straight up die rather than consuming the AD effect.

**Comment by Wilcalaf** [comment]
I currently dont see any problem with the spell.
I tested on a paladin with 109k HP.
This was the result
![image](https://user-images.githubusercontent.com/9047365/44825171-02226f00-ac12-11e8-83e2-affff03afbf0.png)

https://gyazo.com/81467b46dfa394a2d1a0fd64dc6f4fba

he got heal of 17415

seems to be working properly.

please check your logs after the fight you might be have getting it all along but dying after it anyway since 15% is not that much, or maybe you mistimedly used it and it faded just before you died...

**Comment by virpyre** [comment]
@Gubbyfishy Where were you using AD when it failed to heal you?

**Comment by Gubbyfishy** [comment]
I might have just been smacked when I used it last time. It's not that good of a death cooldown anymore I guess...

I'll give it a go on Gamon when I am available

@Wilcalaf It works as intended btw, just weaker than I remembered it. Feel free to close :)
