### ISSUE TITLE
A client not working, IS A BUG.

### ISSUE THREAD

**Issue by ghost** [NRG-Wow/NRGWow-Bugtracker#29]
Fyi,
https://github.com/NRG-Wow/NRGWow-Bugtracker/issues/18
is a bug. Stop acting like bosses around here if you want your server to work properly.You've just started, and I think you might need all the help to get you running properly. After I got that response, I could easily go for a better server, and I'm sure many others proceeded like me, WITHOUT EVEN TRYING, to post something.
First of all, you don't even have a forum. I AM NOT going on discord to report a TECHNICAL ISSUE. So don't tell me, that I did a mistake by reporting here. At least, I wanted to help. 
**Your client not launching is a pretty big deal I'd say. More important than a quest not working.**

So next time you close my thread and send me to Discord, think again.

Best of luck.

**Comment by Wilcalaf** [comment]
@Nescu Helping through discord or any other chat is more effective for this kind of issues. if you want your issue resolved fast you can hop on discord and ask for assitance and it would be solved in minutes
here besides you might wait long time to get a reply, and since this is not a bug on the core or server side it shouldnt be here.

**"Your client not launching is a pretty big deal I'd say. More important than a quest not working."**

Exactly, thats why we need to handle your support directly on discord instead of you waiting for us to be free to check here.
