### ISSUE TITLE
Omen of Clarity

### ISSUE THREAD

**Issue by spotterd** [NRG-Wow/NRGWow-Bugtracker#40]
**Reporter(Player/Character) Name**: Spotterd

**Description**: Describe the problem

Omen of Clarity Clearcasting does not give a 100% mana reduction to: Regrowth, Nourish.

**Current behaviour**: What happens

Uses mana when using Regrowth, Nourish while having Clearcasting.

**Expected behaviour**: What should happen instead

Should give 100% mana reduction to: Regrowth, Nourish.

**Steps to reproduce the problem**:

1. Get Clearcasting
2. Use Regrowth, Nourish

**Comment by Wilcalaf** [comment]
Confirmed for Nourish but not for Regrowth, for Regrowth it was properly giving the mana reduction in all tests
Thanks for report it'll be fixed soon.

**Comment by Illusie** [comment]
Because it should not work on Nourish.
source:
https://www.wow-freakz.com/spells.php?spell=16870

Next time please do not open bugreport on things without bringing a source.
as we said on Discord many times, Simcraft, EJ, Another sites, or another pservers(doubt).
I know its new server and this things are  unprofessional, on other pservers issues like that w/o source/proof are close.

**Comment by Wilcalaf** [comment]
@Illusie 
Thanks for reference.
I wont just close a bug report without at least checking if i can reproduce the problem
we are not solving the bugs right away. we first verify if it even can be reproduced.
after that when we reach to the point we have time to deal with it it will come up as not valid like on this posts
https://us.battle.net/forums/en/wow/topic/2369880843
https://us.battle.net/forums/en/wow/topic/2369880843
https://us.battle.net/forums/en/wow/topic/2046835896
