### ISSUE TITLE
[Cata][Npc][Quest]Warchief's Emissary

### ISSUE THREAD

**Issue by TeenWolf2** [NRG-Wow/NRGWow-Bugtracker#9]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

[//]: # (Please write the titles of the issues following the format:)
[//]: # ([CATA][Quests][Zones] Quest name)
[//]: # ([WOTLK][Spells][Classes] Spell name)
[//]: # ([WOTLK][Talents][Classes] Talent name)
[//]: # ([CATA][Glyphs][Classes] Glyph name)
[//]: # ([CATA][NPCs] NPC name)

**Reporter(Player/Character) Name**: Zoom

**Description**: Npc named Sassy HardWrench doesent exist on boat
**Current behaviour**: Final quest on lost isles .. on the bout that should take player out of lost isles quest requires player to speak to npc named Sassy Hardwrench and she should take u to orgrimar , on this boat Sassy Hardwrench doesent exist , she exists on some other part of Lost isles but not in this one . Boat is located in Gallywix docks

**Expected behaviour**: Npc named Sassy Hardwrench should exist and should take player to orgrimar
**Steps to reproduce the problem**:

1. 
2. 
3.

**Comment by Wilcalaf** [comment]
Hey there, thanks for report. this is a specific case that happened to some players due the disconnections and rollbacks that were caused by the attacks leaving you in wrong phase but with the quest completed.
Its not happening on regular scenarios and it should be ok after the attacks have been mitigated
